version: "3"

services:
  pgadmin:
    container_name: be-database-monitor
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAI}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "7327:80"
    #restart: unless-stopped

volumes:
  pgadmin:
